FROM node:10.16.3-alpine\

#Chromium
ENV CHROME_BIN="/usr/bin/chromium-browser" \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    udev \
    ttf-freefont \
    chromium \

# installs
# shared
WORKDIR /usr/src/shared
COPY ./shared/package*.json ./
RUN npm install --only=production

# compiler
WORKDIR /usr/src/compiler
COPY ./compiler/package*.json ./
RUN npm remove shared
RUN npm install --only=production

# mario-level-generator
WORKDIR /usr/src/mario-level-generator
COPY ./mario-level-generator/package*.json ./
RUN npm remove shared
RUN npm install --only=production

# frontend
WORKDIR /usr/src/frontend
COPY ./frontend/package*.json ./
RUN npm remove shared
RUN npm install --only=production

# backend
WORKDIR /usr/src/backend
COPY ./backend/package*.json ./
RUN npm remove compiler
RUN npm remove shared
RUN npm install --only=production

# compiling
#shared
WORKDIR /usr/src/shared
COPY ./shared/ ./
RUN npm run build

#compiler
WORKDIR /usr/src/compiler
RUN npm install --save ../shared
COPY ./compiler/ ./
RUN npm run build

#mario-level-generator
WORKDIR /usr/src/mario-level-generator
RUN npm install --save ../shared
COPY ./mario-level-generator/ ./
RUN npm run build

#frontend
WORKDIR /usr/src/frontend
RUN npm install --save ../shared
COPY ./frontend/ ./
RUN npm run build

#backend
WORKDIR /usr/src/backend
RUN npm install --save ../shared
RUN npm install --save ../compiler
RUN npm install --save ../mario-level-generator
COPY ./backend/ ./
RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start"]