export default
`
# PLACE AN OBJECT
(3,10) QUESTION_MARK;

# BOX DRAW EXAMPLE
(0,0)->(100,2) GROUND;

# PIPE EXAMPLE
# COORD OF BOTTOM LEFT AND HEIGHT
(5,3) PIPE 4;

# FLAG POLE EXAMPLE
# COORD OF BOTTOM
(17,3) FLAG;

# SCENERY
# COORD OF BOTTOM LEFT
(6,15) CLOUD 3;
(6,3) BUSH 2;

# VARIABLE EXAMPLE
VAR INITIAL_PLATFORM [
	(0,4) BRICK;
	(1,4) QUESTION_MARK;
	(2,4) BRICK;
	(3,4) QUESTION_MARK;
	(4,4) BRICK;
	(2,0) QUESTION_MARK;
];
(10,10) INITIAL_PLATFORM;
`