export default
`
# PLACE AN OBJECT
(3,10) QUESTION_MARK;

# BOX DRAW EXAMPLE
(0,0)->(100,2) GROUND;

# PIPE EXAMPLE
# COORD OF BOTTOM LEFT AND HEIGHT
(5,3) PIPE 4;

# FLAG POLE EXAMPLE
# COORD OF BOTTOM
(25,3) FLAG;

# SCENERY
# COORD OF BOTTOM LEFT
(6,10) CLOUD 1;
(7,3) BUSH 2;

# VARIABLE EXAMPLE
VAR INITIAL_PLATFORM [
	(0,4) BRICK;
	(1,4) QUESTION_MARK;
	(2,4) BRICK;
	(3,4) QUESTION_MARK;
	(4,4) BRICK;
	(2,0) QUESTION_MARK;
];
(17,8) INITIAL_PLATFORM;

# COORD VARIABLE EXAMPLE
COORD MID_SCREEN (50,0);
(MID_SCREEN, 5) DIAMOND_BRICK;

# COORD MATH EXAMPLE
(MID_SCREEN+5, 5) DIAMOND_BRICK;
`