export default
`
# PLACE AN OBJECT
(16,10) QUESTION_MARK;

# BOX DRAW EXAMPLE
(0,20)->(100,22) GROUND;

# PIPE EXAMPLE
# COORD OF BOTTOM LEFT AND HEIGHT
(24,12) PIPE 4

# FLAG POLE EXAMPLE
# COORD OF BOTTOM
(50,3) FLAG

# SCENERY¡
# COORD OF BOTTOM LEFT
(6,5) CLOUD 3
(6,20) BUSH 2

# VARIABLE EXAMPLE
VAR INITIAL_PLATFORM [
	(0,4) BRICK;
	(1,4) QUESTION_MARK;
	(2,4) BRICK;
	(3,4) QUESTION_MARK;
	(4,4) BRICK;
	(5,0) QUESTION_MARK;
];
(20,6) INITIAL_PLATFORM;
`